version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt || true

  pre_build:
    commands:
      - echo Setting up Git...
      - git config --global user.email “Sunil.bhairi85@gmail.com”
      - git config --global user.name “SunilBhairi”
      - export GIT_REPOSITORY_BRANCH=main
      - git remote add origin $GIT_REPOSITORY_URL || echo "Remote already exists"

  build:
    commands:
      - echo Committing and pushing code...
      - git add .
      - git commit -m "Auto-commit from CodeBuild" || echo "Nothing to commit"
      - git push --set-upstream origin $GIT_REPOSITORY_BRANCH

artifacts:
  files:
    - '**/*'
